name: YaleGWI
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - pytest
  - boto3
  - botocore
  - awscli
  - zarr
  - dask
  - scipy
  - s3fs
  - psutil
  - timm
  - einops
  - polars
  - watchdog
  - omegaconf
  - pip:
    - kagglehub
    - google-auth-oauthlib
    - google-auth-httplib2
    - google-api-python-client
    - monai
    - pytorch-lightning==2.0.0
    - torchmetrics==0.11.4
    - segmentation-models-pytorch
    - webdataset
    - plotly
    - packaging 